sudo: false
language: scala
scala:
   - 2.10.5
   - 2.11.7
jdk:
  - oraclejdk8
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database test;' -U postgres
  - psql test -c 'CREATE EXTENSION IF NOT EXISTS hstore;' -U postgres
  - psql test -c 'CREATE EXTENSION IF NOT EXISTS ltree;' -U postgres
  - psql test -c 'CREATE EXTENSION IF NOT EXISTS citext;' -U postgres
  - psql test -c 'CREATE EXTENSION IF NOT EXISTS postgis;' -U postgres
